/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace CanoeHelper {
  export type WarrantStruct = {
    nonce: BigNumberish;
    validBefore: BigNumberish;
    validAfter: BigNumberish;
    verifyingSigner: AddressLike;
    signature: BytesLike;
  };

  export type WarrantStructOutput = [
    nonce: bigint,
    validBefore: bigint,
    validAfter: bigint,
    verifyingSigner: string,
    signature: string
  ] & {
    nonce: bigint;
    validBefore: bigint;
    validAfter: bigint;
    verifyingSigner: string;
    signature: string;
  };
}

export declare namespace PermitHelper {
  export type PermitStruct = {
    value: BigNumberish;
    nonce: BigNumberish;
    deadline: BigNumberish;
    permitStyle: BigNumberish;
    v: BigNumberish;
    r: BytesLike;
    s: BytesLike;
  };

  export type PermitStructOutput = [
    value: bigint,
    nonce: bigint,
    deadline: bigint,
    permitStyle: bigint,
    v: bigint,
    r: string,
    s: string
  ] & {
    value: bigint;
    nonce: bigint;
    deadline: bigint;
    permitStyle: bigint;
    v: bigint;
    r: string;
    s: string;
  };
}

export interface BaseAggregatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "eip712Domain"
      | "fillQuoteEthToToken"
      | "fillQuoteTokenToEth"
      | "fillQuoteTokenToEthWithPermit"
      | "fillQuoteTokenToToken"
      | "fillQuoteTokenToTokenWithPermit"
      | "paused"
      | "permit2"
      | "swapTargets"
      | "usedWarrantNonces"
      | "validSigners"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EIP712DomainChanged"
      | "OrderFilled"
      | "Paused"
      | "RecipientOverridden"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fillQuoteEthToToken",
    values: [
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      AddressLike,
      CanoeHelper.WarrantStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fillQuoteTokenToEth",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      CanoeHelper.WarrantStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fillQuoteTokenToEthWithPermit",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      PermitHelper.PermitStruct,
      CanoeHelper.WarrantStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fillQuoteTokenToToken",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      CanoeHelper.WarrantStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fillQuoteTokenToTokenWithPermit",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      PermitHelper.PermitStruct,
      CanoeHelper.WarrantStruct
    ]
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "permit2", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swapTargets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usedWarrantNonces",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validSigners",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fillQuoteEthToToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fillQuoteTokenToEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fillQuoteTokenToEthWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fillQuoteTokenToToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fillQuoteTokenToTokenWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "permit2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapTargets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedWarrantNonces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validSigners",
    data: BytesLike
  ): Result;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderFilledEvent {
  export type InputTuple = [
    sender: AddressLike,
    recipient: AddressLike,
    tokenIn: AddressLike,
    tokenOut: AddressLike,
    amountIn: BigNumberish,
    amountOut: BigNumberish,
    feeAmount: BigNumberish,
    target: AddressLike
  ];
  export type OutputTuple = [
    sender: string,
    recipient: string,
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    amountOut: bigint,
    feeAmount: bigint,
    target: string
  ];
  export interface OutputObject {
    sender: string;
    recipient: string;
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    amountOut: bigint;
    feeAmount: bigint;
    target: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecipientOverriddenEvent {
  export type InputTuple = [
    requestedRecipient: AddressLike,
    resolvedRecipient: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    requestedRecipient: string,
    resolvedRecipient: string,
    reason: string
  ];
  export interface OutputObject {
    requestedRecipient: string;
    resolvedRecipient: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BaseAggregator extends BaseContract {
  connect(runner?: ContractRunner | null): BaseAggregator;
  waitForDeployment(): Promise<this>;

  interface: BaseAggregatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  fillQuoteEthToToken: TypedContractMethod<
    [
      buyTokenAddress: AddressLike,
      target: AddressLike,
      swapCallData: BytesLike,
      feeAmount: BigNumberish,
      recipient: AddressLike,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;

  fillQuoteTokenToEth: TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      target: AddressLike,
      approvalTarget: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feePercentageBasisPoints: BigNumberish,
      recipient: AddressLike,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;

  fillQuoteTokenToEthWithPermit: TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      target: AddressLike,
      approvalTarget: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feePercentageBasisPoints: BigNumberish,
      recipient: AddressLike,
      permitData: PermitHelper.PermitStruct,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;

  fillQuoteTokenToToken: TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      buyTokenAddress: AddressLike,
      target: AddressLike,
      approvalTarget: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feeAmount: BigNumberish,
      recipient: AddressLike,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;

  fillQuoteTokenToTokenWithPermit: TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      buyTokenAddress: AddressLike,
      target: AddressLike,
      approvalTarget: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feeAmount: BigNumberish,
      recipient: AddressLike,
      permitData: PermitHelper.PermitStruct,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;

  paused: TypedContractMethod<[], [boolean], "view">;

  permit2: TypedContractMethod<[], [string], "view">;

  swapTargets: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  usedWarrantNonces: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  validSigners: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fillQuoteEthToToken"
  ): TypedContractMethod<
    [
      buyTokenAddress: AddressLike,
      target: AddressLike,
      swapCallData: BytesLike,
      feeAmount: BigNumberish,
      recipient: AddressLike,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "fillQuoteTokenToEth"
  ): TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      target: AddressLike,
      approvalTarget: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feePercentageBasisPoints: BigNumberish,
      recipient: AddressLike,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "fillQuoteTokenToEthWithPermit"
  ): TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      target: AddressLike,
      approvalTarget: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feePercentageBasisPoints: BigNumberish,
      recipient: AddressLike,
      permitData: PermitHelper.PermitStruct,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "fillQuoteTokenToToken"
  ): TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      buyTokenAddress: AddressLike,
      target: AddressLike,
      approvalTarget: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feeAmount: BigNumberish,
      recipient: AddressLike,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "fillQuoteTokenToTokenWithPermit"
  ): TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      buyTokenAddress: AddressLike,
      target: AddressLike,
      approvalTarget: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feeAmount: BigNumberish,
      recipient: AddressLike,
      permitData: PermitHelper.PermitStruct,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "permit2"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "swapTargets"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "usedWarrantNonces"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "validSigners"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "OrderFilled"
  ): TypedContractEvent<
    OrderFilledEvent.InputTuple,
    OrderFilledEvent.OutputTuple,
    OrderFilledEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RecipientOverridden"
  ): TypedContractEvent<
    RecipientOverriddenEvent.InputTuple,
    RecipientOverriddenEvent.OutputTuple,
    RecipientOverriddenEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "OrderFilled(address,address,address,address,uint256,uint256,uint256,address)": TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;
    OrderFilled: TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RecipientOverridden(address,address,string)": TypedContractEvent<
      RecipientOverriddenEvent.InputTuple,
      RecipientOverriddenEvent.OutputTuple,
      RecipientOverriddenEvent.OutputObject
    >;
    RecipientOverridden: TypedContractEvent<
      RecipientOverriddenEvent.InputTuple,
      RecipientOverriddenEvent.OutputTuple,
      RecipientOverriddenEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
