/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CanoeHelper {
  export type WarrantStruct = {
    nonce: BigNumberish;
    validBefore: BigNumberish;
    validAfter: BigNumberish;
    verifyingSigner: AddressLike;
    signature: BytesLike;
  };

  export type WarrantStructOutput = [
    nonce: bigint,
    validBefore: bigint,
    validAfter: bigint,
    verifyingSigner: string,
    signature: string
  ] & {
    nonce: bigint;
    validBefore: bigint;
    validAfter: bigint;
    verifyingSigner: string;
    signature: string;
  };
}

export declare namespace PermitHelper {
  export type PermitStruct = {
    value: BigNumberish;
    nonce: BigNumberish;
    deadline: BigNumberish;
    permitStyle: BigNumberish;
    v: BigNumberish;
    r: BytesLike;
    s: BytesLike;
  };

  export type PermitStructOutput = [
    value: bigint,
    nonce: bigint,
    deadline: bigint,
    permitStyle: bigint,
    v: bigint,
    r: string,
    s: string
  ] & {
    value: bigint;
    nonce: bigint;
    deadline: bigint;
    permitStyle: bigint;
    v: bigint;
    r: string;
    s: string;
  };
}

export interface OkuRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "eip712Domain"
      | "fillQuoteEthToToken"
      | "fillQuoteTokenToEth"
      | "fillQuoteTokenToEthWithPermit"
      | "fillQuoteTokenToToken"
      | "fillQuoteTokenToTokenWithPermit"
      | "name"
      | "owner"
      | "pause"
      | "paused"
      | "pendingOwner"
      | "permit2"
      | "renounceOwnership"
      | "swapTargets"
      | "sweepAll"
      | "transferOwnership"
      | "unpause"
      | "updateSwapTargets"
      | "updateValidSigner"
      | "usedWarrantNonces"
      | "validSigners"
      | "version"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContractPaused"
      | "ContractUnpaused"
      | "EIP712DomainChanged"
      | "EthWithdrawn"
      | "OrderFilled"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "Paused"
      | "SwapTargetAdded"
      | "SwapTargetRemoved"
      | "TokenWithdrawn"
      | "Unpaused"
      | "ValidSignerAdded"
      | "ValidSignerRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fillQuoteEthToToken",
    values: [
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      CanoeHelper.WarrantStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fillQuoteTokenToEth",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      CanoeHelper.WarrantStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fillQuoteTokenToEthWithPermit",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      PermitHelper.PermitStruct,
      CanoeHelper.WarrantStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fillQuoteTokenToToken",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      CanoeHelper.WarrantStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fillQuoteTokenToTokenWithPermit",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      PermitHelper.PermitStruct,
      CanoeHelper.WarrantStruct
    ]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "permit2", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapTargets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sweepAll",
    values: [AddressLike[], boolean, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateSwapTargets",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateValidSigner",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "usedWarrantNonces",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validSigners",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fillQuoteEthToToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fillQuoteTokenToEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fillQuoteTokenToEthWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fillQuoteTokenToToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fillQuoteTokenToTokenWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "permit2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapTargets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sweepAll", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateSwapTargets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateValidSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedWarrantNonces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validSigners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace ContractPausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractUnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EthWithdrawnEvent {
  export type InputTuple = [target: AddressLike, amount: BigNumberish];
  export type OutputTuple = [target: string, amount: bigint];
  export interface OutputObject {
    target: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderFilledEvent {
  export type InputTuple = [
    sender: AddressLike,
    tokenIn: AddressLike,
    tokenOut: AddressLike,
    amountIn: BigNumberish,
    amountOut: BigNumberish,
    feeAmount: BigNumberish,
    target: AddressLike
  ];
  export type OutputTuple = [
    sender: string,
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    amountOut: bigint,
    feeAmount: bigint,
    target: string
  ];
  export interface OutputObject {
    sender: string;
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    amountOut: bigint;
    feeAmount: bigint;
    target: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapTargetAddedEvent {
  export type InputTuple = [target: AddressLike];
  export type OutputTuple = [target: string];
  export interface OutputObject {
    target: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapTargetRemovedEvent {
  export type InputTuple = [target: AddressLike];
  export type OutputTuple = [target: string];
  export interface OutputObject {
    target: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenWithdrawnEvent {
  export type InputTuple = [
    token: AddressLike,
    target: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, target: string, amount: bigint];
  export interface OutputObject {
    token: string;
    target: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidSignerAddedEvent {
  export type InputTuple = [target: AddressLike];
  export type OutputTuple = [target: string];
  export interface OutputObject {
    target: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidSignerRemovedEvent {
  export type InputTuple = [target: AddressLike];
  export type OutputTuple = [target: string];
  export interface OutputObject {
    target: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OkuRouter extends BaseContract {
  connect(runner?: ContractRunner | null): OkuRouter;
  waitForDeployment(): Promise<this>;

  interface: OkuRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  fillQuoteEthToToken: TypedContractMethod<
    [
      buyTokenAddress: AddressLike,
      target: AddressLike,
      swapCallData: BytesLike,
      feeAmount: BigNumberish,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;

  fillQuoteTokenToEth: TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      target: AddressLike,
      approvalTarget: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feePercentageBasisPoints: BigNumberish,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;

  fillQuoteTokenToEthWithPermit: TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      target: AddressLike,
      approvalTarget: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feePercentageBasisPoints: BigNumberish,
      permitData: PermitHelper.PermitStruct,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;

  fillQuoteTokenToToken: TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      buyTokenAddress: AddressLike,
      target: AddressLike,
      approvalTarget: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feeAmount: BigNumberish,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;

  fillQuoteTokenToTokenWithPermit: TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      buyTokenAddress: AddressLike,
      target: AddressLike,
      approvalTarget: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feeAmount: BigNumberish,
      permitData: PermitHelper.PermitStruct,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  permit2: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  swapTargets: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  sweepAll: TypedContractMethod<
    [tokens: AddressLike[], includeEth: boolean, to: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateSwapTargets: TypedContractMethod<
    [target: AddressLike, add: boolean],
    [void],
    "nonpayable"
  >;

  updateValidSigner: TypedContractMethod<
    [target: AddressLike, add: boolean],
    [void],
    "nonpayable"
  >;

  usedWarrantNonces: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  validSigners: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  version: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fillQuoteEthToToken"
  ): TypedContractMethod<
    [
      buyTokenAddress: AddressLike,
      target: AddressLike,
      swapCallData: BytesLike,
      feeAmount: BigNumberish,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "fillQuoteTokenToEth"
  ): TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      target: AddressLike,
      approvalTarget: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feePercentageBasisPoints: BigNumberish,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "fillQuoteTokenToEthWithPermit"
  ): TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      target: AddressLike,
      approvalTarget: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feePercentageBasisPoints: BigNumberish,
      permitData: PermitHelper.PermitStruct,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "fillQuoteTokenToToken"
  ): TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      buyTokenAddress: AddressLike,
      target: AddressLike,
      approvalTarget: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feeAmount: BigNumberish,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "fillQuoteTokenToTokenWithPermit"
  ): TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      buyTokenAddress: AddressLike,
      target: AddressLike,
      approvalTarget: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feeAmount: BigNumberish,
      permitData: PermitHelper.PermitStruct,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "permit2"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "swapTargets"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "sweepAll"
  ): TypedContractMethod<
    [tokens: AddressLike[], includeEth: boolean, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateSwapTargets"
  ): TypedContractMethod<
    [target: AddressLike, add: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateValidSigner"
  ): TypedContractMethod<
    [target: AddressLike, add: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usedWarrantNonces"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "validSigners"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ContractPaused"
  ): TypedContractEvent<
    ContractPausedEvent.InputTuple,
    ContractPausedEvent.OutputTuple,
    ContractPausedEvent.OutputObject
  >;
  getEvent(
    key: "ContractUnpaused"
  ): TypedContractEvent<
    ContractUnpausedEvent.InputTuple,
    ContractUnpausedEvent.OutputTuple,
    ContractUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "EthWithdrawn"
  ): TypedContractEvent<
    EthWithdrawnEvent.InputTuple,
    EthWithdrawnEvent.OutputTuple,
    EthWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "OrderFilled"
  ): TypedContractEvent<
    OrderFilledEvent.InputTuple,
    OrderFilledEvent.OutputTuple,
    OrderFilledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "SwapTargetAdded"
  ): TypedContractEvent<
    SwapTargetAddedEvent.InputTuple,
    SwapTargetAddedEvent.OutputTuple,
    SwapTargetAddedEvent.OutputObject
  >;
  getEvent(
    key: "SwapTargetRemoved"
  ): TypedContractEvent<
    SwapTargetRemovedEvent.InputTuple,
    SwapTargetRemovedEvent.OutputTuple,
    SwapTargetRemovedEvent.OutputObject
  >;
  getEvent(
    key: "TokenWithdrawn"
  ): TypedContractEvent<
    TokenWithdrawnEvent.InputTuple,
    TokenWithdrawnEvent.OutputTuple,
    TokenWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "ValidSignerAdded"
  ): TypedContractEvent<
    ValidSignerAddedEvent.InputTuple,
    ValidSignerAddedEvent.OutputTuple,
    ValidSignerAddedEvent.OutputObject
  >;
  getEvent(
    key: "ValidSignerRemoved"
  ): TypedContractEvent<
    ValidSignerRemovedEvent.InputTuple,
    ValidSignerRemovedEvent.OutputTuple,
    ValidSignerRemovedEvent.OutputObject
  >;

  filters: {
    "ContractPaused(address)": TypedContractEvent<
      ContractPausedEvent.InputTuple,
      ContractPausedEvent.OutputTuple,
      ContractPausedEvent.OutputObject
    >;
    ContractPaused: TypedContractEvent<
      ContractPausedEvent.InputTuple,
      ContractPausedEvent.OutputTuple,
      ContractPausedEvent.OutputObject
    >;

    "ContractUnpaused(address)": TypedContractEvent<
      ContractUnpausedEvent.InputTuple,
      ContractUnpausedEvent.OutputTuple,
      ContractUnpausedEvent.OutputObject
    >;
    ContractUnpaused: TypedContractEvent<
      ContractUnpausedEvent.InputTuple,
      ContractUnpausedEvent.OutputTuple,
      ContractUnpausedEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "EthWithdrawn(address,uint256)": TypedContractEvent<
      EthWithdrawnEvent.InputTuple,
      EthWithdrawnEvent.OutputTuple,
      EthWithdrawnEvent.OutputObject
    >;
    EthWithdrawn: TypedContractEvent<
      EthWithdrawnEvent.InputTuple,
      EthWithdrawnEvent.OutputTuple,
      EthWithdrawnEvent.OutputObject
    >;

    "OrderFilled(address,address,address,uint256,uint256,uint256,address)": TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;
    OrderFilled: TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "SwapTargetAdded(address)": TypedContractEvent<
      SwapTargetAddedEvent.InputTuple,
      SwapTargetAddedEvent.OutputTuple,
      SwapTargetAddedEvent.OutputObject
    >;
    SwapTargetAdded: TypedContractEvent<
      SwapTargetAddedEvent.InputTuple,
      SwapTargetAddedEvent.OutputTuple,
      SwapTargetAddedEvent.OutputObject
    >;

    "SwapTargetRemoved(address)": TypedContractEvent<
      SwapTargetRemovedEvent.InputTuple,
      SwapTargetRemovedEvent.OutputTuple,
      SwapTargetRemovedEvent.OutputObject
    >;
    SwapTargetRemoved: TypedContractEvent<
      SwapTargetRemovedEvent.InputTuple,
      SwapTargetRemovedEvent.OutputTuple,
      SwapTargetRemovedEvent.OutputObject
    >;

    "TokenWithdrawn(address,address,uint256)": TypedContractEvent<
      TokenWithdrawnEvent.InputTuple,
      TokenWithdrawnEvent.OutputTuple,
      TokenWithdrawnEvent.OutputObject
    >;
    TokenWithdrawn: TypedContractEvent<
      TokenWithdrawnEvent.InputTuple,
      TokenWithdrawnEvent.OutputTuple,
      TokenWithdrawnEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "ValidSignerAdded(address)": TypedContractEvent<
      ValidSignerAddedEvent.InputTuple,
      ValidSignerAddedEvent.OutputTuple,
      ValidSignerAddedEvent.OutputObject
    >;
    ValidSignerAdded: TypedContractEvent<
      ValidSignerAddedEvent.InputTuple,
      ValidSignerAddedEvent.OutputTuple,
      ValidSignerAddedEvent.OutputObject
    >;

    "ValidSignerRemoved(address)": TypedContractEvent<
      ValidSignerRemovedEvent.InputTuple,
      ValidSignerRemovedEvent.OutputTuple,
      ValidSignerRemovedEvent.OutputObject
    >;
    ValidSignerRemoved: TypedContractEvent<
      ValidSignerRemovedEvent.InputTuple,
      ValidSignerRemovedEvent.OutputTuple,
      ValidSignerRemovedEvent.OutputObject
    >;
  };
}
