/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IPermit2 {
  export type TokenPermissionsStruct = {
    token: AddressLike;
    amount: BigNumberish;
  };

  export type TokenPermissionsStructOutput = [token: string, amount: bigint] & {
    token: string;
    amount: bigint;
  };

  export type PermitTransferFromStruct = {
    permitted: IPermit2.TokenPermissionsStruct;
    nonce: BigNumberish;
    deadline: BigNumberish;
  };

  export type PermitTransferFromStructOutput = [
    permitted: IPermit2.TokenPermissionsStructOutput,
    nonce: bigint,
    deadline: bigint
  ] & {
    permitted: IPermit2.TokenPermissionsStructOutput;
    nonce: bigint;
    deadline: bigint;
  };
}

export interface Permit2ProxyInterface extends Interface {
  getFunction(
    nameOrSignature: "execute" | "executeAllowance" | "okuRouter" | "permit2"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "execute",
    values: [
      IPermit2.PermitTransferFromStruct,
      BytesLike,
      AddressLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeAllowance",
    values: [AddressLike, BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "okuRouter", values?: undefined): string;
  encodeFunctionData(functionFragment: "permit2", values?: undefined): string;

  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "okuRouter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "permit2", data: BytesLike): Result;
}

export interface Permit2Proxy extends BaseContract {
  connect(runner?: ContractRunner | null): Permit2Proxy;
  waitForDeployment(): Promise<this>;

  interface: Permit2ProxyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  execute: TypedContractMethod<
    [
      permit: IPermit2.PermitTransferFromStruct,
      signature: BytesLike,
      buyToken: AddressLike,
      routerCalldata: BytesLike
    ],
    [void],
    "payable"
  >;

  executeAllowance: TypedContractMethod<
    [
      sellToken: AddressLike,
      sellAmount: BigNumberish,
      buyToken: AddressLike,
      routerCalldata: BytesLike
    ],
    [void],
    "payable"
  >;

  okuRouter: TypedContractMethod<[], [string], "view">;

  permit2: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [
      permit: IPermit2.PermitTransferFromStruct,
      signature: BytesLike,
      buyToken: AddressLike,
      routerCalldata: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "executeAllowance"
  ): TypedContractMethod<
    [
      sellToken: AddressLike,
      sellAmount: BigNumberish,
      buyToken: AddressLike,
      routerCalldata: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "okuRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "permit2"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
