// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity >=0.7.0;

interface IMetaAggregationRouterV2 {
    // This struct and the parameters for the main swap function can vary.
    // This is a common pattern where the router executes a series of calls.
    // The actual data for 'swapData' would come from KyberSwap's API.
    struct SwapDescription {
        address srcToken;
        address dstToken;
        address srcReceiver;
        address dstReceiver;
        uint256 amount;
        uint256 minReturnAmount;
        uint256 flags; // For specific behaviors
        bytes permit; // Optional permit data for srcToken
    }

    // The primary function to execute a swap using data from KyberSwap's API.
    // The exact name and parameters can differ slightly based on the deployed version.
    // It often involves the token being spent, the amount, and the trade data.
    // Sometimes it's a more generic `execute` or a specifically named `swap`.
    function swap(
        address tokenIn,
        uint256 amountIn,
        address tokenOut, // May not be needed if encoded in swapCallData
        uint256 amountOutMin, // Or this might be part of swapCallData
        address to, // recipient, may also be part of swapCallData
        bytes calldata swapCallData // This is the critical part from Kyber's API
    ) external payable returns (uint256 returnAmount);

    // Another common pattern for aggregator routers:
    // function execute(bytes calldata data) external payable returns (bytes memory result);

    // Or specifically for swaps:
    // struct TradeDetails {
    //     address tokenIn;
    //     address tokenOut;
    //     uint256 amountIn;
    //     uint256 minAmountOut;
    //     address recipient;
    //     bytes tradeData; // The crucial API-provided data
    //     // Potentially deadline, permit data etc.
    // }
    // function processRoute(
    //     address tokenIn,
    //     uint256 amountIn,
    //     address tokenOut,
    //     uint256 minExpectedAmount, // slippage control
    //     address recipient,
    //     bytes calldata pathPayload, // data from API describing the path
    //     bytes calldata permit // EIP-2612 permit data
    // ) external payable returns (uint256 actualAmountOut);

    // The most important thing is to get the ABI for the *specific router address*
    // you are using on the target chain. For 0x6131B5fae19EA4f9D964eAc0408E4408b66337b5,
    // a common function looks like this:
    // function swap(
    //     IERC20 tokenIn,
    //     uint256 amountIn,
    //     uint256 minReturn,
    //     bytes calldata _swapDescription // This is generated by their API
    // ) external payable returns (uint256 returnAmount);

    // Based on inspecting typical aggregator routers and Kyber's documentation structure,
    // the swap function often looks like it will take a blob of data that defines
    // the actual path and parameters, which your `generateKyberSwapTxData` would fetch from Kyber's API.
    //
    // If you are targeting `0x6131b5fae19ea4f9d964eac0408e4408b66337b5`, the `swap` function
    // often has a signature that includes `executor`, `desc`, and `permit` or similar, where `desc`
    // contains the core routing logic provided by the API.
    //
    // Example structure found in some Kyber Aggregators:
    // struct ExecutorInput {
    //    address tokenIn;
    //    uint256 amountIn;
    //    uint256 amountOutMin;
    //    address recipient;
    //    bytes trade; // This 'trade' or 'route' bytes comes from the API
    //    bytes permit2; // For token approvals via Permit2
    //}
    // function execute(ExecutorInput calldata input) external payable returns (uint256 amountOut);

    // The most consistently seen function for MetaAggregationRouterV2 (0x6131...)
    // takes a `routeSummary` (often as part of a larger struct or directly as bytes)
    // which is obtained from the KyberSwap API.
    //
    // function swap(
    //     address executor, // The address performing the swap, often the router itself or a helper
    //     SwapDescription calldata desc, // Contains tokenIn, tokenOut, amountIn, recipient, etc.
    //     bytes calldata permit, // Optional permit string for tokenIn
    //     bytes calldata route // This is the critical part from the API defining the path
    // ) external payable returns (uint256 returnAmount);
}