/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOkuRouter,
  IOkuRouterInterface,
} from "../../../contracts/interfaces/IOkuRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sellTokenAddress",
        type: "address",
      },
      {
        internalType: "address payable",
        name: "target",
        type: "address",
      },
      {
        internalType: "address",
        name: "approvalTarget",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "swapCallData",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "sellAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "feePercentageBasisPoints",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint160",
            name: "nonce",
            type: "uint160",
          },
          {
            internalType: "uint48",
            name: "validBefore",
            type: "uint48",
          },
          {
            internalType: "uint48",
            name: "validAfter",
            type: "uint48",
          },
          {
            internalType: "address",
            name: "verifyingSigner",
            type: "address",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct CanoeHelper.Warrant",
        name: "warrant",
        type: "tuple",
      },
    ],
    name: "fillQuoteTokenToEth",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "sellTokenAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "buyTokenAddress",
        type: "address",
      },
      {
        internalType: "address payable",
        name: "target",
        type: "address",
      },
      {
        internalType: "address",
        name: "approvalTarget",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "swapCallData",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "sellAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "feeAmount",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint160",
            name: "nonce",
            type: "uint160",
          },
          {
            internalType: "uint48",
            name: "validBefore",
            type: "uint48",
          },
          {
            internalType: "uint48",
            name: "validAfter",
            type: "uint48",
          },
          {
            internalType: "address",
            name: "verifyingSigner",
            type: "address",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct CanoeHelper.Warrant",
        name: "warrant",
        type: "tuple",
      },
    ],
    name: "fillQuoteTokenToToken",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IOkuRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IOkuRouterInterface {
    return new Interface(_abi) as IOkuRouterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IOkuRouter {
    return new Contract(address, _abi, runner) as unknown as IOkuRouter;
  }
}
