/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace CanoeHelper {
  export type WarrantStruct = {
    nonce: BigNumberish;
    validBefore: BigNumberish;
    validAfter: BigNumberish;
    verifyingSigner: AddressLike;
    signature: BytesLike;
  };

  export type WarrantStructOutput = [
    nonce: bigint,
    validBefore: bigint,
    validAfter: bigint,
    verifyingSigner: string,
    signature: string
  ] & {
    nonce: bigint;
    validBefore: bigint;
    validAfter: bigint;
    verifyingSigner: string;
    signature: string;
  };
}

export interface IOkuRouterInterface extends Interface {
  getFunction(
    nameOrSignature: "fillQuoteTokenToEth" | "fillQuoteTokenToToken"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "fillQuoteTokenToEth",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      CanoeHelper.WarrantStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fillQuoteTokenToToken",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      CanoeHelper.WarrantStruct
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "fillQuoteTokenToEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fillQuoteTokenToToken",
    data: BytesLike
  ): Result;
}

export interface IOkuRouter extends BaseContract {
  connect(runner?: ContractRunner | null): IOkuRouter;
  waitForDeployment(): Promise<this>;

  interface: IOkuRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  fillQuoteTokenToEth: TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      target: AddressLike,
      approvalTarget: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feePercentageBasisPoints: BigNumberish,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;

  fillQuoteTokenToToken: TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      buyTokenAddress: AddressLike,
      target: AddressLike,
      approvalTarget: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feeAmount: BigNumberish,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "fillQuoteTokenToEth"
  ): TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      target: AddressLike,
      approvalTarget: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feePercentageBasisPoints: BigNumberish,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "fillQuoteTokenToToken"
  ): TypedContractMethod<
    [
      sellTokenAddress: AddressLike,
      buyTokenAddress: AddressLike,
      target: AddressLike,
      approvalTarget: AddressLike,
      swapCallData: BytesLike,
      sellAmount: BigNumberish,
      feeAmount: BigNumberish,
      warrant: CanoeHelper.WarrantStruct
    ],
    [void],
    "payable"
  >;

  filters: {};
}
