/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iKyberSwapRouterSol from "./IKyberSwapRouter.sol";
export type { iKyberSwapRouterSol };
export type { IOKXDexRouter } from "./IOKXDexRouter";
