/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IOKXDexRouter {
  export type BaseRequestStruct = {
    fromToken: AddressLike;
    toToken: AddressLike;
    fromTokenAmount: BigNumberish;
    minReturnAmount: BigNumberish;
    deadLine: BigNumberish;
  };

  export type BaseRequestStructOutput = [
    fromToken: string,
    toToken: string,
    fromTokenAmount: bigint,
    minReturnAmount: bigint,
    deadLine: bigint
  ] & {
    fromToken: string;
    toToken: string;
    fromTokenAmount: bigint;
    minReturnAmount: bigint;
    deadLine: bigint;
  };
}

export interface IOKXDexRouterInterface extends Interface {
  getFunction(
    nameOrSignature: "dagSwapTo" | "smartSwapTo" | "uniswapV3SwapTo"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "dagSwapTo",
    values: [IOKXDexRouter.BaseRequestStruct, BytesLike, boolean, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "smartSwapTo",
    values: [IOKXDexRouter.BaseRequestStruct, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapV3SwapTo",
    values: [IOKXDexRouter.BaseRequestStruct, BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "dagSwapTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "smartSwapTo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapV3SwapTo",
    data: BytesLike
  ): Result;
}

export interface IOKXDexRouter extends BaseContract {
  connect(runner?: ContractRunner | null): IOKXDexRouter;
  waitForDeployment(): Promise<this>;

  interface: IOKXDexRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  dagSwapTo: TypedContractMethod<
    [
      baseRequest: IOKXDexRouter.BaseRequestStruct,
      callDataConcat: BytesLike,
      useInternalBalance: boolean,
      toAddress: AddressLike
    ],
    [bigint],
    "payable"
  >;

  smartSwapTo: TypedContractMethod<
    [
      baseRequest: IOKXDexRouter.BaseRequestStruct,
      callDataConcat: BytesLike,
      toAddress: AddressLike
    ],
    [bigint],
    "payable"
  >;

  uniswapV3SwapTo: TypedContractMethod<
    [
      baseRequest: IOKXDexRouter.BaseRequestStruct,
      callDataConcat: BytesLike,
      toAddress: AddressLike
    ],
    [bigint],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "dagSwapTo"
  ): TypedContractMethod<
    [
      baseRequest: IOKXDexRouter.BaseRequestStruct,
      callDataConcat: BytesLike,
      useInternalBalance: boolean,
      toAddress: AddressLike
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "smartSwapTo"
  ): TypedContractMethod<
    [
      baseRequest: IOKXDexRouter.BaseRequestStruct,
      callDataConcat: BytesLike,
      toAddress: AddressLike
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "uniswapV3SwapTo"
  ): TypedContractMethod<
    [
      baseRequest: IOKXDexRouter.BaseRequestStruct,
      callDataConcat: BytesLike,
      toAddress: AddressLike
    ],
    [bigint],
    "payable"
  >;

  filters: {};
}
