/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iKyberSwapRouterSol from "./IKyberSwapRouter.sol";
export { IOKXDexRouter__factory } from "./IOKXDexRouter__factory";
