/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOKXDexRouter,
  IOKXDexRouterInterface,
} from "../../../../contracts/interfaces/aggregators/IOKXDexRouter";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "fromToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "toToken",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "fromTokenAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minReturnAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "deadLine",
            type: "uint256",
          },
        ],
        internalType: "struct IOKXDexRouter.BaseRequest",
        name: "baseRequest",
        type: "tuple",
      },
      {
        internalType: "bytes",
        name: "callDataConcat",
        type: "bytes",
      },
      {
        internalType: "bool",
        name: "useInternalBalance",
        type: "bool",
      },
      {
        internalType: "address",
        name: "toAddress",
        type: "address",
      },
    ],
    name: "dagSwapTo",
    outputs: [
      {
        internalType: "uint256",
        name: "returnAmount",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "fromToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "toToken",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "fromTokenAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minReturnAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "deadLine",
            type: "uint256",
          },
        ],
        internalType: "struct IOKXDexRouter.BaseRequest",
        name: "baseRequest",
        type: "tuple",
      },
      {
        internalType: "bytes",
        name: "callDataConcat",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "toAddress",
        type: "address",
      },
    ],
    name: "smartSwapTo",
    outputs: [
      {
        internalType: "uint256",
        name: "returnAmount",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "fromToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "toToken",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "fromTokenAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minReturnAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "deadLine",
            type: "uint256",
          },
        ],
        internalType: "struct IOKXDexRouter.BaseRequest",
        name: "baseRequest",
        type: "tuple",
      },
      {
        internalType: "bytes",
        name: "callDataConcat",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "toAddress",
        type: "address",
      },
    ],
    name: "uniswapV3SwapTo",
    outputs: [
      {
        internalType: "uint256",
        name: "returnAmount",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IOKXDexRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IOKXDexRouterInterface {
    return new Interface(_abi) as IOKXDexRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IOKXDexRouter {
    return new Contract(address, _abi, runner) as unknown as IOKXDexRouter;
  }
}
