/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  CanoeHelper,
  CanoeHelperInterface,
} from "../../../contracts/libraries/CanoeHelper";

const _abi = [
  {
    inputs: [],
    name: "EIP712_CANOE_WARRANT_TYPE",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "TYPEHASH_CANOE_WARRANT",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234601957610193908161001f823930815050f35b600080fdfe6080604052600436101561001257600080fd5b60003560e01c806368b74d9e1461005b576395a9641f1461003257600080fd5b60003660031901126100565760206100486100be565b818151910120604051908152f35b600080fd5b60003660031901126100565761006f6100be565b60405190602082528181519182602083015260005b8381106100a65750508160006040809484010152601f80199101168101030190f35b60208282018101516040878401015285935001610084565b604051906060820182811067ffffffffffffffff82111761012e57604052603b82527f6174696f6e446174612c627974657333322064617461486173682900000000006040837f43616e6f6557617272616e742875696e74323536207061636b656456616c696460208201520152565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fdfea2646970667358221220fa5a23f6888820959bd4afda45c1883220f835a7be3de954d1d1ea0f5d035abb64736f6c634300081b0033";

type CanoeHelperConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CanoeHelperConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CanoeHelper__factory extends ContractFactory {
  constructor(...args: CanoeHelperConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      CanoeHelper & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): CanoeHelper__factory {
    return super.connect(runner) as CanoeHelper__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CanoeHelperInterface {
    return new Interface(_abi) as CanoeHelperInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): CanoeHelper {
    return new Contract(address, _abi, runner) as unknown as CanoeHelper;
  }
}
