/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface CanoeHelperInterface extends Interface {
  getFunction(
    nameOrSignature: "EIP712_CANOE_WARRANT_TYPE" | "TYPEHASH_CANOE_WARRANT"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "EIP712_CANOE_WARRANT_TYPE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TYPEHASH_CANOE_WARRANT",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "EIP712_CANOE_WARRANT_TYPE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TYPEHASH_CANOE_WARRANT",
    data: BytesLike
  ): Result;
}

export interface CanoeHelper extends BaseContract {
  connect(runner?: ContractRunner | null): CanoeHelper;
  waitForDeployment(): Promise<this>;

  interface: CanoeHelperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  EIP712_CANOE_WARRANT_TYPE: TypedContractMethod<[], [string], "view">;

  TYPEHASH_CANOE_WARRANT: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "EIP712_CANOE_WARRANT_TYPE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TYPEHASH_CANOE_WARRANT"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
