/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMetaAggregationRouterV2,
  IMetaAggregationRouterV2Interface,
} from "../../../../../contracts/interfaces/aggregators/IKyberSwapRouter.sol/IMetaAggregationRouterV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountOutMin",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "swapCallData",
        type: "bytes",
      },
    ],
    name: "swap",
    outputs: [
      {
        internalType: "uint256",
        name: "returnAmount",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IMetaAggregationRouterV2__factory {
  static readonly abi = _abi;
  static createInterface(): IMetaAggregationRouterV2Interface {
    return new Interface(_abi) as IMetaAggregationRouterV2Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMetaAggregationRouterV2 {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IMetaAggregationRouterV2;
  }
}
